package appgestores.views;

import appgestores.Sistema;
import appgestores.controllers.gestor.GestorController;
import appgestores.controllers.gestor.UIGestor;
import entidades.Pedido;
import java.awt.Font;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan, Ignacio
 */
public class FrmGestores extends javax.swing.JFrame implements UIGestor {

    private GestorController controller;

    /**
     * Creates new form FrmGestores
     */
    public FrmGestores() {
        try {
            initComponents();
            setLocationRelativeTo(null);
            controller = new GestorController(Sistema.getService(), this, Sistema.getUnidadProcesadora());
            lblGestor.setText(Sistema.getGestor().getNombre());
            panelMisPedidos.hide();
            panelTodosLosPedidos.show();
        } catch (RemoteException ex) {
            Logger.getLogger(FrmGestores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUser = new javax.swing.JPanel();
        lblIconUser = new javax.swing.JLabel();
        lblGestor = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        lblMisPedidos = new javax.swing.JLabel();
        lblPedidos = new javax.swing.JLabel();
        lblServicios = new javax.swing.JLabel();
        panellAll = new javax.swing.JPanel();
        panelMisPedidos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMisPedidos = new javax.swing.JList<>();
        btnFinalizarPedido = new javax.swing.JButton();
        panelTodosLosPedidos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPedidos = new javax.swing.JList<>();
        btnTomarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelUser.setBackground(new java.awt.Color(77, 11, 232));

        lblIconUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appgestores/views/resources/imgs/user.png"))); // NOI18N

        lblGestor.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 15)); // NOI18N
        lblGestor.setForeground(new java.awt.Color(255, 255, 255));

        btnCerrar.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrar.setText("x");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });

        lblMisPedidos.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        lblMisPedidos.setForeground(new java.awt.Color(255, 255, 255));
        lblMisPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMisPedidos.setText("Pedidos tomados");
        lblMisPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMisPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMisPedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMisPedidosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMisPedidosMousePressed(evt);
            }
        });

        lblPedidos.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        lblPedidos.setForeground(new java.awt.Color(255, 255, 255));
        lblPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPedidos.setText("Todos los pedidos");
        lblPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPedidos.setMaximumSize(new java.awt.Dimension(133, 16));
        lblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPedidosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPedidosMousePressed(evt);
            }
        });

        lblServicios.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        lblServicios.setForeground(new java.awt.Color(255, 255, 255));
        lblServicios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServicios.setText("Servicios");
        lblServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblServicios.setMaximumSize(new java.awt.Dimension(133, 16));
        lblServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblServiciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblServiciosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblServiciosMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelUserLayout = new javax.swing.GroupLayout(panelUser);
        panelUser.setLayout(panelUserLayout);
        panelUserLayout.setHorizontalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconUser, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblMisPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserLayout.createSequentialGroup()
                    .addContainerGap(756, Short.MAX_VALUE)
                    .addComponent(lblServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(48, 48, 48)))
        );
        panelUserLayout.setVerticalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUserLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblMisPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblIconUser, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(lblGestor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelUserLayout.createSequentialGroup()
                        .addComponent(btnCerrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUserLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panellAll.setLayout(new java.awt.CardLayout());

        panelMisPedidos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Mis pedidos");

        lstMisPedidos.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        lstMisPedidos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstMisPedidos);

        btnFinalizarPedido.setBackground(new java.awt.Color(77, 11, 232));
        btnFinalizarPedido.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        btnFinalizarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizarPedido.setText("Finalizar pedido");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMisPedidosLayout = new javax.swing.GroupLayout(panelMisPedidos);
        panelMisPedidos.setLayout(panelMisPedidosLayout);
        panelMisPedidosLayout.setHorizontalGroup(
            panelMisPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMisPedidosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelMisPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMisPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelMisPedidosLayout.setVerticalGroup(
            panelMisPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMisPedidosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
        );

        panellAll.add(panelMisPedidos, "card2");

        panelTodosLosPedidos.setBackground(new java.awt.Color(255, 255, 255));
        panelTodosLosPedidos.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Pedidos");

        lstPedidos.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        lstPedidos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstPedidos);

        btnTomarPedido.setBackground(new java.awt.Color(77, 11, 232));
        btnTomarPedido.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        btnTomarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnTomarPedido.setText("Tomar pedido");
        btnTomarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTodosLosPedidosLayout = new javax.swing.GroupLayout(panelTodosLosPedidos);
        panelTodosLosPedidos.setLayout(panelTodosLosPedidosLayout);
        panelTodosLosPedidosLayout.setHorizontalGroup(
            panelTodosLosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTodosLosPedidosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelTodosLosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTomarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTodosLosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panelTodosLosPedidosLayout.setVerticalGroup(
            panelTodosLosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTodosLosPedidosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTomarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panellAll.add(panelTodosLosPedidos, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panellAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panellAll, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        cerrar();
    }//GEN-LAST:event_btnCerrarMousePressed

    private void lblMisPedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMisPedidosMouseEntered
        lblMisPedidos.setFont(new Font("Lucida Sans Unicode", 1, 18));
    }//GEN-LAST:event_lblMisPedidosMouseEntered

    private void lblMisPedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMisPedidosMouseExited
        lblMisPedidos.setFont(new Font("Lucida Sans Unicode", 1, 14));
    }//GEN-LAST:event_lblMisPedidosMouseExited

    private void lblMisPedidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMisPedidosMousePressed
        panelTodosLosPedidos.hide();
        panelMisPedidos.show();
    }//GEN-LAST:event_lblMisPedidosMousePressed

    private void lblPedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedidosMouseEntered
        lblPedidos.setFont(new Font("Lucida Sans Unicode", 1, 18));
    }//GEN-LAST:event_lblPedidosMouseEntered

    private void lblPedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedidosMouseExited
        lblPedidos.setFont(new Font("Lucida Sans Unicode", 1, 13));
    }//GEN-LAST:event_lblPedidosMouseExited

    private void lblPedidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedidosMousePressed
        panelMisPedidos.hide();
        panelTodosLosPedidos.show();
    }//GEN-LAST:event_lblPedidosMousePressed

    private void btnTomarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarPedidoActionPerformed
        controller.tomarPedido();
    }//GEN-LAST:event_btnTomarPedidoActionPerformed

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed
        controller.finalizarPedido();
    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed

    private void lblServiciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServiciosMouseEntered
        lblServicios.setFont(new Font("Lucida Sans Unicode", 1, 18));
    }//GEN-LAST:event_lblServiciosMouseEntered

    private void lblServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServiciosMouseExited
        lblServicios.setFont(new Font("Lucida Sans Unicode", 1, 14));
    }//GEN-LAST:event_lblServiciosMouseExited

    private void lblServiciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServiciosMousePressed
        JDListadoServicios frm = new JDListadoServicios(this, false);
        frm.setVisible(true);
    }//GEN-LAST:event_lblServiciosMousePressed

    private void cerrar() {
        int res = JOptionPane.showConfirmDialog(this, "¿Desea cerrar sesión?", "Atención", JOptionPane.YES_NO_OPTION);
        if (res == 0) {
            controller.cerrarSesion();
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JButton btnTomarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGestor;
    private javax.swing.JLabel lblIconUser;
    private javax.swing.JLabel lblMisPedidos;
    private javax.swing.JLabel lblPedidos;
    private javax.swing.JLabel lblServicios;
    private javax.swing.JList<Object> lstMisPedidos;
    private javax.swing.JList<Object> lstPedidos;
    private javax.swing.JPanel panelMisPedidos;
    private javax.swing.JPanel panelTodosLosPedidos;
    private javax.swing.JPanel panelUser;
    private javax.swing.JPanel panellAll;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarMensaje(String msg, String titulo, int opt) {
        JOptionPane.showMessageDialog(this, msg, titulo, opt);
    }

    @Override
    public void listarPedidos(ArrayList<Pedido> col) {
        lstPedidos.setListData(col.toArray());
    }

    @Override
    public Pedido getPedidoTomar() {
        if (lstPedidos.getSelectedIndex() > -1) {
            return (Pedido) lstPedidos.getSelectedValue();
        }
        return null;
    }

    @Override
    public void listarMisPedidos(ArrayList<Pedido> lista) {
        lstMisPedidos.setListData(lista.toArray());
    }

    @Override
    public Pedido getPedidoFinalizar() {
        if (lstMisPedidos.getSelectedIndex() > -1) {
            return (Pedido) lstMisPedidos.getSelectedValue();
        }
        return null;
    }
}
